### ISSUE TITLE
Patron Name with UTF8 char wrongly displayed

### ISSUE THREAD

**Issue by martinkoehler** [join2/SIPServer#2]
Patron names with Umlauts do not display properly
e.g. Borrower M1351 (Martin Köhler) is shown as
similar to Martin K|-ahler
May be fixed by setting correct encoding in easycheck config ?

**Comment by aw-bib** [comment]
Does easycheck expect Windows ANSI?

**Comment by martinkoehler** [comment]
The config has "850" as codepage.
Changing this to utf-8 or 65001 (which is utf-8 as codepage) does not help.
So probably I have to translate everything to cp850?

**Comment by aw-bib** [comment]
Sounds like. cp850 very nice. Last saw it as default on OS/2 :)
